{
 "title": "Central Unit - Control Plane (CU - CP)",
 "time": { "from": "2023-05-23T15:15:21.000Z", "to": "2023-05-23T15:15:23.000Z" },
 "panels": [
  {
   "title": "L3servingSINR",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "SELECT \"value\" FROM /L3servingSINR_cell_[0-5]/ WHERE $timeFilter\n"
    }
   ]
  },
  {
   "title": "L3neighSINR3",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "query": "SELECT \"value\" FROM /L3neighSINR3_cell_[0-5]/ WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "L3neighSINR1",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "query": "SELECT \"value\" FROM /L3neighSINR1_cell_[0-5]/ WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "L3neighId2 ",
   "type": "timeseries",
   "description": "cellId",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "query": "SELECT \"value\" FROM /L3neighId2\\(cellId\\)_cell_[0-5]/ WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "L3neighSINR2",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "query": "SELECT \"value\" FROM /L3neighSINR2_cell_[0-5]/ WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "L3neighId3",
   "type": "timeseries",
   "description": "cellId",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "query": "SELECT \"value\" FROM /L3neighId3\\(cellId\\)_cell_[0-5]/ WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "L3neighId1",
   "type": "timeseries",
   "description": "cellId",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "query": "SELECT \"value\" FROM /L3neighId1\\(cellId\\)_cell_[0-5]/ WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "DRB_EstabSucc_5QI_UEID",
   "type": "timeseries",
   "description": "numDrb",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "query": "SELECT \"value\" FROM /DRB_EstabSucc_5QI_UEID\\(numDrb\\)_[0-9]{5}_cp/ WHERE $timeFilter"
    }
   ]
  }
 ]
}