{
 "title": "Central Unit - User Plane (CU - UP)",
 "time": { "from": "2023-09-16T11:28:02.604Z", "to": "2023-09-16T11:28:03.426Z" },
 "panels": [
  {
   "title": "PDCP PDU Volume",
   "type": "timeseries",
   "description": "txPdcpPduBytesNrRlc",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kbits" } },
   "targets": [
    {
     "query": "SELECT \"value\" FROM /QosFlow_PdcpPduVolumeDL_Filter_UEID\\(txPdcpPduBytesNrRlc\\)_[0-9]{5}_up/ WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "Cell PDCP Latency",
   "type": "timeseries",
   "description": "pdcpLatency",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pdcp_latency",
     "query": "SELECT \"value\" FROM /DRB.PdcpSduDelayDl.UEID\\(pdcpLatency\\)_[0-9]{5}_up/ WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "metric_type", "operator": "=", "value": "gauge" }
     ]
    }
   ]
  },
  {
   "title": "QoS PDCP PDU",
   "type": "timeseries",
   "description": "txPdcpPduNrRlc",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "kbit" } },
   "targets": [
    {
     "query": "SELECT \"value\" FROM /DRB_PdcpPduNbrDl_Qos_UEID\\(txPdcpPduNrRlc\\)_[0-9]{5}_up/ WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "Cell Average Latency",
   "type": "timeseries",
   "description": "cellAverageLatency",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "query": "SELECT \"value\" FROM /DRB.PdcpSduDelayDl\\(cellAverageLatency\\)_cell_[0-9]/ WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "PDCP PDU",
   "type": "timeseries",
   "description": "txDlPackets",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "packets" } },
   "targets": [
    {
     "query": "SELECT \"value\" FROM /Tot_PdcpSduNbrDl_UEID\\(txDlPackets\\)_[0-9]{5}_up/ WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "PDCP Throughput",
   "type": "timeseries",
   "description": "pdcpThroughput",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "kbps" } },
   "targets": [
    {
     "query": "SELECT \"value\" FROM /DRB.PdcpSduBitRateDl.UEID\\(pdcpThroughput\\)_[0-9]{5}_up/ WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "Cell PDCP Volume",
   "type": "timeseries",
   "description": " cellDlTxVolume",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "kbit" } },
   "targets": [
    {
     "query": "SELECT \"value\" FROM /m_pDCPBytesDL\\(cellDlTxVolume\\)_cell_[0-9]/ WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "Tx Bytes",
   "type": "timeseries",
   "description": "txBytes",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "kbit" } },
   "targets": [
    {
     "query": "SELECT \"value\" FROM /DRB.PdcpSduVolumeDl_Filter.UEID\\(txBytes\\)_[0-9]{5}_up/ WHERE $timeFilter"
    }
   ]
  }
 ]
}