{
 "title": "Cp_Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "numActiveUes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "SELECT \"value\" FROM /numActiveUes_[0-9]{5}_cp/ WHERE $timeFilter\n"
    }
   ]
  },
  {
   "title": "L3neighSINR3gpp2 (convertedSinr)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "SELECT \"value\" FROM /L3neighSINR3gpp2\\(convertedSinr\\)_[0-9]{5}_cp/ WHERE $timeFilter\n"
    }
   ]
  },
  {
   "title": "L3servingSINR",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "SELECT \"value\" FROM /L3servingSINR_[0-9]{5}_cp/ WHERE $timeFilter\n"
    }
   ]
  },
  {
   "title": "L3neighSINR3",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "query": "SELECT \"value\" FROM /L3neighSINR3_[0-9]{5}_cp/ WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "L3servingSINR3gpp",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "query": "SELECT \"value\" FROM /L3servingSINR3gpp_[0-9]{5}_cp/ WHERE $timeFilter\n"
    }
   ]
  },
  {
   "title": "L3neighSINR1",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "query": "SELECT \"value\" FROM /L3neighSINR1_[0-9]{5}_cp/ WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "L3servingId (m_cellId)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "query": "SELECT \"value\" FROM /L3servingId\\(m_cellId\\)_[0-9]{5}_cp/ WHERE $timeFilter\n"
    }
   ]
  },
  {
   "title": "L3neighId2 (cellId)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "query": "SELECT \"value\" FROM /L3neighId2\\(cellId\\)_[0-9]{5}_cp/ WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "L3neighSINR3gpp1 (convertedSinr)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "query": "SELECT \"value\" FROM /L3neighSINR3gpp1\\(convertedSinr\\)_[0-9]{5}_cp/ WHERE $timeFilter\n"
    }
   ]
  },
  {
   "title": "DRB_RelActNbr_5QI_UEID",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "query": "SELECT \"value\" FROM /DRB_RelActNbr_5QI_UEID\\(0\\)_[0-9]{5}_cp/ WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "L3neighSINR3gpp3 (convertedSinr)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "query": "SELECT \"value\" FROM /L3neighSINR3gpp3\\(convertedSinr\\)_[0-9]{5}_cp/ WHERE $timeFilter\n"
    }
   ]
  },
  {
   "title": "L3neighSINR2",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "query": "SELECT \"value\" FROM /L3neighSINR2_[0-9]{5}_cp/ WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "L3neighId3 (cellId)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "query": "SELECT \"value\" FROM /L3neighId3\\(cellId\\)_[0-9]{5}_cp/ WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "L3neighId1 (cellId)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "targets": [
    {
     "query": "SELECT \"value\" FROM /L3neighId1\\(cellId\\)_[0-9]{5}_cp/ WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "DRB_EstabSucc_5QI_UEID (numDrb)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "query": "SELECT \"value\" FROM /DRB_EstabSucc_5QI_UEID\\(numDrb\\)_[0-9]{5}_cp/ WHERE $timeFilter"
    }
   ]
  }
 ]
}