{
 "title": "Central Unit - Control Plane (CU - CP)",
 "time": { "from": "2023-10-07T19:56:56.381Z", "to": "2023-10-07T19:56:57.491Z" },
 "panels": [
  {
   "title": "SINR from Neighbor Cell 1",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "targets": [
    {
     "query": "SELECT \"value\" FROM /L3neighSINR1_[0-9]{5}_cp/ WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "Neighbor Cell Id 1",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "SELECT \"value\" FROM /L3neighId1\\(cellId\\)_[0-9]{5}_cp/ WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "SINR from Neighbor Cell 2",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "targets": [
    {
     "query": "SELECT \"value\" FROM /L3neighSINR2_[0-9]{5}_cp/ WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "Neighbor Cell Id 2",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "query": "SELECT \"value\" FROM /L3neighId2\\(cellId\\)_[0-9]{5}_cp/ WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "SINR from Neighbor Cell 3",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "targets": [
    {
     "query": "SELECT \"value\" FROM /L3neighSINR3_[0-9]{5}_cp/ WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "Neighbor Cell Id 3",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "SELECT \"value\" FROM /L3neighId3\\(cellId\\)_[0-5]{5}_cp/ WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "SINR from Serving Cell",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "targets": [
    {
     "query": "SELECT \"value\" FROM /L3servingSINR_[0-9]{5}_cp/ WHERE $timeFilter\n"
    }
   ]
  },
  {
   "title": "Serving Cell Id",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "query": "SELECT \"value\" FROM /L3servingID_[0-9]{5}_cp/ WHERE $timeFilter\n"
    }
   ]
  },
  {
   "title": "Data Radio Bearer Establishment Success 5G Quality Identifier",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "query": "SELECT \"value\" FROM /DRB_EstabSucc_5QI_UEID\\(numDrb\\)_[0-9]{5}_cp/ WHERE $timeFilter"
    }
   ]
  }
 ]
}