{
 "title": "Central Unit - User Plane (CU - UP)",
 "time": { "from": "2023-10-07T14:05:57.575Z", "to": "2023-10-07T14:06:00.933Z" },
 "panels": [
  {
   "title": "QoS PDCP PDU per UE",
   "type": "timeseries",
   "description": "only gNB (cell 2, 3, 4 and 5)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kbit" } },
   "targets": [
    {
     "query": "SELECT \"value\" FROM /DRB_PdcpPduNbrDl_Qos_UEID\\(txPdcpPduNrRlc\\)_[0-9]{5}_up/ WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "PDCP PDU Volume per UE",
   "type": "timeseries",
   "description": "only gNB (cell 2, 3, 4 and 5)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kbits" } },
   "targets": [
    {
     "query": "SELECT \"value\" FROM /QosFlow_PdcpPduVolumeDL_Filter_UEID\\(txPdcpPduBytesNrRlc\\)_[0-9]{5}_up/ WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "PDCP PDU TX DL Packets per UE",
   "type": "timeseries",
   "description": "only eNB (cell 1)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "packets" } },
   "targets": [
    {
     "query": "SELECT \"value\" FROM /Tot_PdcpSduNbrDl_UEID\\(txDlPackets\\)_[0-9]{5}_up/ WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "Cell PDCP Latency per UE",
   "type": "timeseries",
   "description": "only eNB (cell 1)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pdcp_latency",
     "query": "SELECT \"value\" FROM /DRB.PdcpSduDelayDl.UEID\\(pdcpLatency\\)_[0-9]{5}_up/ WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "metric_type", "operator": "=", "value": "gauge" }
     ]
    }
   ]
  },
  {
   "title": "Tx Bytes per UE",
   "type": "timeseries",
   "description": "only eNB (cell 1)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "kbit" } },
   "targets": [
    {
     "query": "SELECT \"value\" FROM /DRB.PdcpSduVolumeDl_Filter.UEID\\(txBytes\\)_[0-9]{5}_up/ WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "PDCP Throughput per UE",
   "type": "timeseries",
   "description": "only eNB (cell 1)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "kbps" } },
   "targets": [
    {
     "query": "SELECT \"value\" FROM /DRB.PdcpSduBitRateDl.UEID\\(pdcpThroughput\\)_[0-9]{5}_up/ WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "Cell Average Latency per Cell",
   "type": "timeseries",
   "description": "only eNB (cell 1)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "query": "SELECT \"value\" FROM /DRB.PdcpSduDelayDl\\(cellAverageLatency\\)_cell_[0-9]/ WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "Cell PDCP Volume per Cell",
   "type": "timeseries",
   "description": "only eNB (cell 1)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "kbit" } },
   "targets": [
    {
     "query": "SELECT \"value\" FROM /m_pDCPBytesDL\\(cellDlTxVolume\\)_cell_[0-9]/ WHERE $timeFilter"
    }
   ]
  }
 ]
}