{
 "title": "Distributed Unit (DU)",
 "time": { "from": "2023-05-23T15:15:21.000Z", "to": "2023-05-23T15:15:23.000Z" },
 "panels": [
  {
   "title": "TB_ErrTotalNbrDl_1_UEID",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "SELECT \"value\" FROM /TB_ErrTotalNbrDl_1_UEID_[0-9]{5}_du/ WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "L1M_RS-SINR_Bin127",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "SELECT \"value\" FROM /L1M_RS-SINR_Bin127_[0-9]{5}_du/ WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "TB_ErrTotalNbrDl_1",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "SELECT \"value\" FROM /TB_ErrTotalNbrDl_1_[0-9]{5}_du/ WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "DRB_MeanActiveUeDl",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "query": "SELECT \"value\" FROM /DRB_MeanActiveUeDl_[0-9]{5}_du/ WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "RRU_PrbUsedDl_UEID",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "query": "SELECT \"value\" FROM /RRU_PrbUsedDl_UEID_[0-9]{5}_du/ WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "DRB_BufferSize_Qos",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "query": "SELECT \"value\" FROM /DRB_BufferSize_Qos_[0-9]{5}_du/ WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "RRU_PrbUsedDl",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "query": "SELECT \"value\" FROM /RRU_PrbUsedDl_[0-9]{5}_du/ WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "CARR_PDSCHMCSDist_Bin6",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "query": "SELECT \"value\" FROM /CARR_PDSCHMCSDist_Bin6_[0-9]{5}_du/ WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "QosFlow_PdcpPduVolumeDL_Filter_UEID",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "query": "SELECT \"value\" FROM /QosFlow_PdcpPduVolumeDL_Filter_UEID_[0-9]{5}_du/ WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "CARR_PDSCHMCSDist_Bin5",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "query": "SELECT \"value\" FROM /CARR_PDSCHMCSDist_Bin5_[0-9]{5}_du/ WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "QosFlow_PdcpPduVolumeDL_Filter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "query": "SELECT \"value\" FROM /QosFlow_PdcpPduVolumeDL_Filter_[0-9]{5}_du/ WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "CARR_PDSCHMCSDist_Bin4",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "query": "SELECT \"value\" FROM /CARR_PDSCHMCSDist_Bin4_[0-9]{5}_du/ WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "L1M_RS-SINR_Bin94",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "query": "SELECT \"value\" FROM /L1M_RS-SINR_Bin94_[0-9]{5}_du/ WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "CARR_PDSCHMCSDist_Bin3",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "targets": [
    {
     "query": "SELECT \"value\" FROM /CARR_PDSCHMCSDist_Bin3_[0-9]{5}_du/ WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "L1M_RS-SINR_Bin94_UEID",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "query": "SELECT \"value\" FROM /L1M_RS-SINR_Bin94_UEID_[0-9]{5}_du/ WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "CARR_PDSCHMCSDist_Bin2",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "targets": [
    {
     "query": "SELECT \"value\" FROM /CARR_PDSCHMCSDist_Bin2_[0-9]{5}_du/ WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "L1M_RS-SINR_Bin82_UEID",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "targets": [
    {
     "query": "SELECT \"value\" FROM /L1M_RS-SINR_Bin82_UEID_[0-9]{5}_du/ WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "CARR_PDSCHMCSDist_Bin1",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "targets": [
    {
     "query": "SELECT \"value\" FROM /CARR_PDSCHMCSDist_Bin1_[0-9]{5}_du/ WHERE $timeFilter\n"
    }
   ]
  },
  {
   "title": "L1M_RS-SINR_Bin82",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "targets": [
    {
     "query": "SELECT \"value\" FROM /L1M_RS-SINR_Bin82_[0-9]{5}_du/ WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "CARR_PDSCHMCSDist_Bin1_UEID",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 72 },
   "targets": [
    {
     "query": "SELECT \"value\" FROM /CARR_PDSCHMCSDist_Bin1_UEID_[0-9]{5}_du/ WHERE $timeFilter\n"
    }
   ]
  },
  {
   "title": "L1M_RS-SINR_Bin70",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 80 },
   "targets": [
    {
     "query": "SELECT \"value\" FROM /L1M_RS-SINR_Bin70_[0-9]{5}_du/ WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "CARR_PDSCHMCSDist_Bin2_UEID",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 80 },
   "targets": [
    {
     "query": "SELECT \"value\" FROM /CARR_PDSCHMCSDist_Bin2_UEID_[0-9]{5}_du/ WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "L1M_RS-SINR_Bin70_UEID",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 88 },
   "targets": [
    {
     "query": "SELECT \"value\" FROM /L1M_RS-SINR_Bin70_UEID_[0-9]{5}_du/ WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "CARR_PDSCHMCSDist_Bin3_UEID",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 88 },
   "targets": [
    {
     "query": "SELECT \"value\" FROM /CARR_PDSCHMCSDist_Bin3_UEID_[0-9]{5}_du/ WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "L1M_RS-SINR_Bin58_UEID",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 96 },
   "targets": [
    {
     "query": "SELECT \"value\" FROM /L1M_RS-SINR_Bin58_UEID_[0-9]{5}_du/ WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "CARR_PDSCHMCSDist_Bin4_UEID",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 96 },
   "targets": [
    {
     "query": "SELECT \"value\" FROM /CARR_PDSCHMCSDist_Bin4_UEID_[0-9]{5}_du/ WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "L1M_RS-SINR_Bin58",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 104 },
   "targets": [
    {
     "query": "SELECT \"value\" FROM /L1M_RS-SINR_Bin58_[0-9]{5}_du/ WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "CARR_PDSCHMCSDist_Bin5_UEID",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 104 },
   "targets": [
    {
     "query": "SELECT \"value\" FROM /CARR_PDSCHMCSDist_Bin5_UEID_[0-9]{5}_du/ WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "L1M_RS-SINR_Bin46_UEID",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 112 },
   "targets": [
    {
     "query": "SELECT \"value\" FROM /L1M_RS-SINR_Bin46_UEID_[0-9]{5}_du/ WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "CARR_PDSCHMCSDist_Bin6_UEID",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 112 },
   "targets": [
    {
     "query": "SELECT \"value\" FROM /CARR_PDSCHMCSDist_Bin6_UEID_[0-9]{5}_du/ WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "L1M_RS-SINR_Bin46",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 120 },
   "targets": [
    {
     "query": "SELECT \"value\" FROM /L1M_RS-SINR_Bin46_[0-9]{5}_du/ WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "DRB_BufferSize_Qos_UEID",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 120 },
   "targets": [
    {
     "query": "SELECT \"value\" FROM /DRB_BufferSize_Qos_UEID_[0-9]{5}_du/ WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "L1M_RS-SINR_Bin34_UEID",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 128 },
   "targets": [
    {
     "query": "SELECT \"value\" FROM /L1M_RS-SINR_Bin34_UEID_[0-9]{5}_du/ WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "DRB_UEThpDlPdcpBased_UEID",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 128 },
   "targets": [
    {
     "query": "SELECT \"value\" FROM /DRB_UEThpDlPdcpBased_UEID_[0-9]{5}_du/ WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "L1M_RS-SINR_Bin34",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 136 },
   "targets": [
    {
     "query": "SELECT \"value\" FROM /L1M_RS-SINR_Bin34_[0-9]{5}_du/ WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "DRB_UEThpDl_UEID",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 136 },
   "targets": [
    {
     "query": "SELECT \"value\" FROM /DRB_UEThpDl_UEID_[0-9]{5}_du/ WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "L1M_RS-SINR_Bin127_UEID",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 144 },
   "targets": [
    {
     "query": "SELECT \"value\" FROM /L1M_RS-SINR_Bin127_UEID_[0-9]{5}_du/ WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "TB_TotNbrDlInitial",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 144 },
   "targets": [
    {
     "query": "SELECT \"value\" FROM /TB_TotNbrDlInitial_[0-9]{5}_du/ WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "TB_TotNbrDlInitial_16Qam",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 152 },
   "targets": [
    {
     "query": "SELECT \"value\" FROM /TB_TotNbrDlInitial_16Qam_[0-9]{5}_du/ WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "TB_TotNbrDlInitial_16Qam_UEID",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 152 },
   "targets": [
    {
     "query": "SELECT \"value\" FROM /TB_TotNbrDlInitial_16Qam_UEID_[0-9]{5}_du/ WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "TB_TotNbrDlInitial_64Qam",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 160 },
   "targets": [
    {
     "query": "SELECT \"value\" FROM /TB_TotNbrDlInitial_64Qam_[0-9]{5}_du/ WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "TB_TotNbrDlInitial_64Qam_UEID",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 160 },
   "targets": [
    {
     "query": "SELECT \"value\" FROM /TB_TotNbrDlInitial_64Qam_UEID_[0-9]{5}_du/ WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "TB_TotNbrDlInitial_Qpsk",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 168 },
   "targets": [
    {
     "query": "SELECT \"value\" FROM /TB_TotNbrDlInitial_Qpsk_[0-9]{5}_du/ WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "TB_TotNbrDlInitial_Qpsk_UEID",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 168 },
   "targets": [
    {
     "query": "SELECT \"value\" FROM /TB_TotNbrDlInitial_Qpsk_UEID_[0-9]{5}_du/ WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "TB_TotNbrDlInitial_UEID",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 176 },
   "targets": [
    {
     "query": "SELECT \"value\" FROM /TB_TotNbrDlInitial_UEID_[0-9]{5}_du/ WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "TB_TotNbrDl_1",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 176 },
   "targets": [
    {
     "query": "SELECT \"value\" FROM /TB_TotNbrDl_1_[0-9]{5}_du/ WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "TB_TotNbrDl_1_UEID",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 184 },
   "targets": [
    {
     "query": "SELECT \"value\" FROM /TB_TotNbrDl_1_UEID_[0-9]{5}_du/ WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "nrCellId",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 184 },
   "targets": [
    {
     "query": "SELECT \"value\" FROM /nrCellId_[0-9]{5}_du/ WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "dlPrbUsage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 192 },
   "targets": [
    {
     "query": "SELECT \"value\" FROM /dlPrbUsage_[0-9]{5}_du/ WHERE $timeFilter"
    }
   ]
  }
 ]
}