{
 "title": "Distributed Unit (DU)",
 "time": { "from": "2023-10-07T14:05:57.070Z", "to": "2023-10-07T14:05:59.976Z" },
 "panels": [
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Block Error Rate in Downlink per UE",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "query": "SELECT \"value\" FROM /TB_ErrTotalNbrDl_1_UEID_[0-9]{5}_du/ WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "Total Block Error Rate in Downlink per Cell",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "query": "SELECT \"value\" FROM /TB_ErrTotalNbrDl_1_cell_[0-5]/ WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "Usage of RRU Physical resource block in Downlink per UE",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "query": "SELECT \"value\" FROM /RRU_PrbUsedDl_UEID_[0-9]{5}_du/ WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "Usage of RRU Physical resource block in Downlink per Cell",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "query": "SELECT \"value\" FROM /RRU_PrbUsedDl_cell_[0-5]/ WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "Volume of PDCP PDU in DL for Qos Flow per UE",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "SELECT \"value\" FROM /QosFlow_PdcpPduVolumeDL_Filter_UEID_[0-9]{5}_du/ WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "Volume of PDCP PDU in DL for Qos Flow per Cell",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "query": "SELECT \"value\" FROM /QosFlow_PdcpPduVolumeDL_Filter_cell_[0-5]/ WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "Total Number of Transport Blocks in Downlink with 16QAM per UE",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "query": "SELECT \"value\" FROM /TB_TotNbrDlInitial_16Qam_UEID_[0-9]{5}_du/ WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "Total Number of Transport Blocks in Downlink with 16QAM per Cell",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "query": "SELECT \"value\" FROM /TB_TotNbrDlInitial_16Qam_cell_[0-5]/ WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "Total Number of Transport Blocks in Downlink with 64QAM per UE",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "query": "SELECT \"value\" FROM /TB_TotNbrDlInitial_64Qam_UEID_[0-9]{5}_du/ WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "Total Number of Transport Blocks in Downlink with 16QAM per Cell",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "query": "SELECT \"value\" FROM /TB_TotNbrDlInitial_64Qam_cell_[0-5]/ WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "Total Number of Transport Blocks in Downlink with QPSK per UE",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "targets": [
    {
     "query": "SELECT \"value\" FROM /TB_TotNbrDlInitial_Qpsk_UEID_[0-9]{5}_du/ WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "Total Number of Transport Blocks in Downlink with QPSK per Cell",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "targets": [
    {
     "query": "SELECT \"value\" FROM /TB_TotNbrDlInitial_Qpsk_cell_[0-5]/ WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "Total Number of Transport Blocks in Downlink per UE",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "targets": [
    {
     "query": "SELECT \"value\" FROM /TB_TotNbrDlInitial_UEID_[0-9]{5}_du/ WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "Total Number of Transport Blocks in Downlink per Cell",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "targets": [
    {
     "query": "SELECT \"value\" FROM /TB_TotNbrDlInitial_cell_[0-5]/ WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "Total Number of Transport Blocks in Downlink per UE",
   "type": "timeseries",
   "description": "this is not only initial",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "targets": [
    {
     "query": "SELECT \"value\" FROM /TB_TotNbrDl_1_UEID_[0-9]{5}_du/ WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "Total Number of Transport Blocks in Downlink per Cell",
   "type": "timeseries",
   "description": "this is not initial only",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
   "targets": [
    {
     "query": "SELECT \"value\" FROM /TB_TotNbrDl_1_cell_[0-5]/ WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "DRB Qos Buffer Size per UE",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "SELECT \"value\" FROM /DRB_BufferSize_Qos_UEID_[0-9]{5}_du/ WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "DRB Qos Buffer Size per Cell",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "SELECT \"value\" FROM /DRB_BufferSize_Qos_cell_[0-5]/ WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "DRB Downlink Throughput per UE",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "kbps" } },
   "targets": [
    {
     "query": "SELECT \"value\" FROM /DRB_UEThpDl_UEID_[0-9]{5}_du/ WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "DRB Downlink Throughput in the PDCP layer per UE",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "kbps" } },
   "targets": [
    {
     "query": "SELECT \"value\" FROM /DRB_UEThpDlPdcpBased_UEID_[0-9]{5}_du/ WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "Usage of Physical resource block in Downlink per Cell",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "SELECT \"value\" FROM /dlPrbUsage_cell_[0-5]/ WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "Mean Active UEs in Downlink per Cell",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 81 },
   "targets": [
    {
     "query": "SELECT \"value\" FROM /DRB_MeanActiveUeDl_cell_[0-5]/ WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "Bin Row",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 89 },
   "collapsed": true,
   "panels": [
    {
     "title": "CARR_PDSCHMCSDist_Bin1_UEID",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 90 },
     "targets": [
      {
       "query": "SELECT \"value\" FROM /CARR_PDSCHMCSDist_Bin1_UEID_[0-9]{5}_du/ WHERE $timeFilter\n"
      }
     ]
    },
    {
     "title": "CARR_PDSCHMCSDist_Bin1",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 90 },
     "targets": [
      {
       "query": "SELECT \"value\" FROM /CARR_PDSCHMCSDist_Bin1_cell_[0-5]/ WHERE $timeFilter\n"
      }
     ]
    },
    {
     "title": "CARR_PDSCHMCSDist_Bin2_UEID",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 98 },
     "targets": [
      {
       "query": "SELECT \"value\" FROM /CARR_PDSCHMCSDist_Bin2_UEID_[0-9]{5}_du/ WHERE $timeFilter"
      }
     ]
    },
    {
     "title": "CARR_PDSCHMCSDist_Bin2",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 98 },
     "targets": [
      {
       "query": "SELECT \"value\" FROM /CARR_PDSCHMCSDist_Bin2_cell_[0-5]/ WHERE $timeFilter"
      }
     ]
    },
    {
     "title": "CARR_PDSCHMCSDist_Bin3_UEID",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 106 },
     "targets": [
      {
       "query": "SELECT \"value\" FROM /CARR_PDSCHMCSDist_Bin3_UEID_[0-9]{5}_du/ WHERE $timeFilter"
      }
     ]
    },
    {
     "title": "CARR_PDSCHMCSDist_Bin3",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 106 },
     "targets": [
      {
       "query": "SELECT \"value\" FROM /CARR_PDSCHMCSDist_Bin3_cell_[0-5]/ WHERE $timeFilter"
      }
     ]
    },
    {
     "title": "CARR_PDSCHMCSDist_Bin4_UEID",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 114 },
     "targets": [
      {
       "query": "SELECT \"value\" FROM /CARR_PDSCHMCSDist_Bin4_UEID_[0-9]{5}_du/ WHERE $timeFilter"
      }
     ]
    },
    {
     "title": "CARR_PDSCHMCSDist_Bin4",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 114 },
     "targets": [
      {
       "query": "SELECT \"value\" FROM /CARR_PDSCHMCSDist_Bin4_cell_[0-5]/ WHERE $timeFilter"
      }
     ]
    },
    {
     "title": "CARR_PDSCHMCSDist_Bin5_UEID",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 122 },
     "targets": [
      {
       "query": "SELECT \"value\" FROM /CARR_PDSCHMCSDist_Bin5_UEID_[0-9]{5}_du/ WHERE $timeFilter"
      }
     ]
    },
    {
     "title": "CARR_PDSCHMCSDist_Bin5",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 122 },
     "targets": [
      {
       "query": "SELECT \"value\" FROM /CARR_PDSCHMCSDist_Bin5_cell_[0-5]/ WHERE $timeFilter"
      }
     ]
    },
    {
     "title": "CARR_PDSCHMCSDist_Bin6_UEID",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 130 },
     "targets": [
      {
       "query": "SELECT \"value\" FROM /CARR_PDSCHMCSDist_Bin6_UEID_[0-9]{5}_du/ WHERE $timeFilter"
      }
     ]
    },
    {
     "title": "CARR_PDSCHMCSDist_Bin6",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 130 },
     "targets": [
      {
       "query": "SELECT \"value\" FROM /CARR_PDSCHMCSDist_Bin6_cell_[0-5]/ WHERE $timeFilter"
      }
     ]
    },
    {
     "title": "L1M_RS-SINR_Bin34_UEID",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 138 },
     "targets": [
      {
       "query": "SELECT \"value\" FROM /L1M_RS-SINR_Bin34_UEID_[0-9]{5}_du/ WHERE $timeFilter"
      }
     ]
    },
    {
     "title": "L1M_RS-SINR_Bin34",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 138 },
     "targets": [
      {
       "query": "SELECT \"value\" FROM /L1M_RS-SINR_Bin34_cell_[0-5]/ WHERE $timeFilter"
      }
     ]
    },
    {
     "title": "L1M_RS-SINR_Bin46",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 146 },
     "targets": [
      {
       "query": "SELECT \"value\" FROM /L1M_RS-SINR_Bin46_cell_[0-5]/ WHERE $timeFilter"
      }
     ]
    },
    {
     "title": "L1M_RS-SINR_Bin46_UEID",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 146 },
     "targets": [
      {
       "query": "SELECT \"value\" FROM /L1M_RS-SINR_Bin46_UEID_[0-9]{5}_du/ WHERE $timeFilter"
      }
     ]
    },
    {
     "title": "L1M_RS-SINR_Bin58_UEID",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 154 },
     "targets": [
      {
       "query": "SELECT \"value\" FROM /L1M_RS-SINR_Bin58_UEID_[0-9]{5}_du/ WHERE $timeFilter"
      }
     ]
    },
    {
     "title": "L1M_RS-SINR_Bin58",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 154 },
     "targets": [
      {
       "query": "SELECT \"value\" FROM /L1M_RS-SINR_Bin58_cell_[0-5]/ WHERE $timeFilter"
      }
     ]
    },
    {
     "title": "L1M_RS-SINR_Bin70_UEID",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 162 },
     "targets": [
      {
       "query": "SELECT \"value\" FROM /L1M_RS-SINR_Bin70_UEID_[0-9]{5}_du/ WHERE $timeFilter"
      }
     ]
    },
    {
     "title": "L1M_RS-SINR_Bin70",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 162 },
     "targets": [
      {
       "query": "SELECT \"value\" FROM /L1M_RS-SINR_Bin70_cell_[0-5]/ WHERE $timeFilter"
      }
     ]
    },
    {
     "title": "L1M_RS-SINR_Bin82_UEID",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 170 },
     "targets": [
      {
       "query": "SELECT \"value\" FROM /L1M_RS-SINR_Bin82_UEID_[0-9]{5}_du/ WHERE $timeFilter"
      }
     ]
    },
    {
     "title": "L1M_RS-SINR_Bin82",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 170 },
     "targets": [
      {
       "query": "SELECT \"value\" FROM /L1M_RS-SINR_Bin82_cell_[0-5]/ WHERE $timeFilter"
      }
     ]
    },
    {
     "title": "L1M_RS-SINR_Bin94_UEID",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 178 },
     "targets": [
      {
       "query": "SELECT \"value\" FROM /L1M_RS-SINR_Bin94_UEID_[0-9]{5}_du/ WHERE $timeFilter"
      }
     ]
    },
    {
     "title": "L1M_RS-SINR_Bin94",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 178 },
     "targets": [
      {
       "query": "SELECT \"value\" FROM /L1M_RS-SINR_Bin94_cell_[0-5]/ WHERE $timeFilter"
      }
     ]
    },
    {
     "title": "L1M_RS-SINR_Bin127_UEID",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 186 },
     "targets": [
      {
       "query": "SELECT \"value\" FROM /L1M_RS-SINR_Bin127_UEID_[0-9]{5}_du/ WHERE $timeFilter"
      }
     ]
    },
    {
     "title": "L1M_RS-SINR_Bin127",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 186 },
     "targets": [
      {
       "query": "SELECT \"value\" FROM /L1M_RS-SINR_Bin127_cell_[0-5]/ WHERE $timeFilter"
      }
     ]
    }
   ]
  }
 ]
}